name: Read build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.RabbitMQ.Read/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.RabbitMQ.Read
      prebuild_command: docker run -d --hostname my-rabbit -p 5672:5672 -p 8080:1567 -e RABBITMQ_DEFAULT_USER=agent -e RABBITMQ_DEFAULT_PASS=agent123  rabbitmq:3.7-management
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}