name: Read build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.RabbitMQ.Read/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.RabbitMQ.Read
      prebuild_command: |
        sudo cp Frends.RabbitMQ.Read.Tests/TestData/certs/ca_certificate.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}